site_name: Django GraphQL Auth
site_description: GraphQL authentication for Django
site_url: https://django-graphql-auth.readthedocs.io/en/latest
site_author: pedrobern
repo_name: pedrobern/django-graphql-auth
repo_url: https://github.com/pedrobern/django-graphql-auth

theme:
  name: "material"
  language: en
  palette:
    primary: 'black'
    accent: 'purple'
  logo: 'images/graphql_logo.svg'
  favicon: 'images/favicon.ico'

extra:
  social:
    - type: github-alt
      link: https://github.com/pedrobern

google_analytics:
  - 'UA-152567868-2'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - markdownextradata:
        data: docs/data

dev_addr: 127.0.0.1:7000

nav:
  - Start here: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Overriding email templates: overriding-email-templates.md
  - Relay: relay.md
  - Settings: settings.md
  - API: api.md
  - Contributing: contributing.md
  - Community: community.md
  - Changelog: changelog.md
  - Contributors: contributors.md
